// AI story categories and templates for GhostWriter
// Family-friendly, with subtle humor for all ages

export const STORY_CATEGORIES = [
  {
    name: "Adventure",
    description: "Exciting journeys, hidden treasures, and daring escapes.",
    templates: [
      "A group of friends discovers a mysterious map in their school library...",
      "Lost in the jungle, a clever monkey helps a young explorer find the way home...",
      "A pirate ship sets sail, but the real treasure is the friends made along the way...",
      "A hot air balloon ride goes off course and lands in a field of giggling goats...",
      "A daring rescue mission to save a rubber duck from the bathtub whirlpool...",
      "A secret tunnel under the playground leads to a world of talking vegetables...",
      "A treasure chest is found, but it's full of mismatched socks...",
      "A mountain climbing adventure where the mountain keeps moving...",
      "A lost puppy leads a group of kids on a wild chase through the city...",
      "A rollercoaster that only goes backwards...",
      "A mysterious island appears in the middle of the local pond...",
      "A sandcastle competition turns into a race against the tide...",
      "A backpack with a mind of its own takes its owner on a wild ride...",
      "A runaway kite leads to an unexpected friendship...",
      "A secret society of squirrels plans the ultimate heist: the nut vault...",
      "A daring escape from a maze made entirely of cheese...",
      "A bicycle race where the bikes keep swapping riders...",
      "A sleepover in a haunted treehouse...",
      "A snowball fight that gets out of hand when the snowballs start rolling themselves...",
      "A canoe trip down a river of chocolate milk...",
      "A mysterious whistle summons a parade of penguins...",
      "A camping trip interrupted by a family of curious raccoons...",
      "A lost key unlocks a door to a world of upside-down rules...",
      "A scavenger hunt with clues that rhyme...",
      "A daring leap across the world's smallest puddle..."
    ]
  },
  {
    name: "Fantasy",
    description: "Magic, mythical creatures, and enchanted lands.",
    templates: [
      "A dragon with a sneezing problem accidentally sets off a chain of magical events...",
      "A wizard's spell goes wrong, turning the town's mayor into a talking frog...",
      "A unicorn with a rainbow tail learns the importance of sharing snacks...",
      "A fairy godparent who keeps mixing up wishes...",
      "A castle made of jellybeans appears overnight...",
      "A talking cat becomes the school principal for a day...",
      "A magic wand that only works on Tuesdays...",
      "A troll under the bridge who loves to tell knock-knock jokes...",
      "A potion that makes everyone speak in rhymes...",
      "A knight who is afraid of his own armor...",
      "A mermaid who wants to be a stand-up comedian...",
      "A magical library where the books read you...",
      "A griffin with a feather allergy...",
      "A wizard's hat that grants wishes, but only for socks...",
      "A kingdom where everyone must hop instead of walk...",
      "A dragon who collects rubber ducks instead of gold...",
      "A magical bakery that sells invisible cupcakes...",
      "A fairy who can't stop giggling during serious meetings...",
      "A spell that turns vegetables into disco dancers...",
      "A talking tree that gives questionable advice...",
      "A princess who prefers mud pies to fancy cakes...",
      "A magic carpet with a flat tire...",
      "A castle moat filled with lemonade...",
      "A wizard duel that turns into a pie fight...",
      "A magical pet rock with big dreams..."
    ]
  },
  {
    name: "Comedy",
    description: "Silly situations, puns, and light-hearted fun.",
    templates: [
      "A banana slips on a human peel and chaos ensues at the fruit market...",
      "A detective dog tries to solve the case of the missing homework, but keeps getting distracted by squirrels...",
      "A superhero whose only power is making people laugh saves the day at a very boring meeting...",
      "A chicken crosses the playground and everyone wants to know why...",
      "A pie-eating contest where the pies eat back...",
      "A prank war between the lunch ladies and the janitors...",
      "A joke so funny it makes the sun sneeze...",
      "A talking sandwich gives life advice...",
      "A school talent show where everyone forgets their act...",
      "A whoopee cushion with a mind of its own...",
      "A family reunion at the zoo, but the animals are the guests...",
      "A spelling bee where the words spell themselves...",
      "A dance party in the library...",
      "A pet hamster runs for class president...",
      "A magician who can only pull out rubber chickens...",
      "A joke book that tells knock-knock jokes all night...",
      "A birthday cake that sings instead of being eaten...",
      "A pair of shoes that can't stop tap dancing...",
      "A hiccuping contest that never ends...",
      "A sleepwalking goldfish causes chaos...",
      "A pizza delivery to the moon...",
      "A backwards day at school...",
      "A prank call from a cow...",
      "A spelling test where the answers are all puns...",
      "A mustache-growing contest for cats..."
    ]
  },
  {
    name: "Mystery",
    description: "Puzzles, secrets, and clever twists.",
    templates: [
      "Someone keeps switching the teacher's coffee with hot chocolate. Who could it be?",
      "A secret door in the school leads to a room full of rubber chickens...",
      "The case of the missing left sock: a tale of suspense and static electricity...",
      "A coded message found in a bowl of alphabet soup...",
      "A missing lunchbox leads to a trail of cookie crumbs...",
      "A locked diary with invisible ink...",
      "A mysterious note left in the principal's shoe...",
      "A riddle that only the class hamster can solve...",
      "A secret handshake that opens a hidden room...",
      "A missing trophy and a trail of glitter...",
      "A library book that returns itself...",
      "A shadowy figure seen only at recess...",
      "A map with moving landmarks...",
      "A classroom pet with a double life...",
      "A mystery guest at the school assembly...",
      "A missing page from the school newspaper...",
      "A coded message in the morning announcements...",
      "A secret admirer who leaves rubber ducks...",
      "A lunch swap gone wrong...",
      "A missing shoe found in the freezer...",
      "A riddle that leads to the janitor's closet...",
      "A mystery smell in the cafeteria...",
      "A secret club with a silly password...",
      "A missing hat found on the class skeleton...",
      "A detective who only works in pajamas..."
    ]
  },
  {
    name: "Sci-Fi",
    description: "Space, robots, and futuristic inventions.",
    templates: [
      "A robot learns to dance, but can't stop doing the worm...",
      "Aliens land on Earth, but only want to try pizza...",
      "A time machine malfunctions, sending a group of kids to the age of disco...",
      "A spaceship powered by bubblegum...",
      "A robot who wants to be a stand-up comedian...",
      "A school on Mars with zero-gravity recess...",
      "A talking computer that only tells jokes...",
      "A teleportation device that swaps shoes instead of people...",
      "A friendly alien who loves knock-knock jokes...",
      "A science fair project that comes to life...",
      "A robot dog with a wagging antenna...",
      "A time traveler who keeps forgetting what year it is...",
      "A space station with a pizza parlor...",
      "A moon colony with a trampoline park...",
      "A robot who can't stop hiccuping...",
      "A spaceship with a leaky window...",
      "A classroom where the teacher is a hologram...",
      "A rocket launch interrupted by a flock of geese...",
      "A robot who wants to learn ballet...",
      "A planet made entirely of cheese...",
      "A space explorer who gets lost in a black hole of socks...",
      "A friendly alien who loves to play hide and seek...",
      "A robot who dreams of being a chef...",
      "A time machine that only goes to lunchtime...",
      "A spaceship with a disco ball..."
    ]
  },
  {
    name: "Sports",
    description: "Games, teamwork, and funny competition moments.",
    templates: [
      "A soccer game where the ball keeps changing color...",
      "A basketball team of penguins...",
      "A relay race where the baton is a banana...",
      "A baseball game interrupted by a parade of ducks...",
      "A swimming race in a pool of jelly...",
      "A tennis match with invisible rackets...",
      "A football team of robots...",
      "A coach who only speaks in rhymes...",
      "A cheerleading squad of frogs...",
      "A tug-of-war with a rope made of spaghetti...",
      "A marathon where everyone runs backwards...",
      "A dodgeball game with balloons...",
      "A hockey game on roller skates...",
      "A golf tournament with rubber chickens...",
      "A referee who can't stop sneezing...",
      "A gymnastics meet with trampoline shoes...",
      "A bowling alley with bouncing pins...",
      "A wrestling match between two teddy bears...",
      "A ping pong game with a beach ball...",
      "A soccer goalie who is afraid of the ball...",
      "A basketball hoop that moves...",
      "A baseball bat that tells jokes...",
      "A swimming coach who can't swim...",
      "A football game with a square ball...",
      "A team mascot who keeps getting lost..."
    ]
  },
  {
    name: "Animals",
    description: "Talking animals, wild adventures, and animal friendships.",
    templates: [
      "A cat who wants to be a dog...",
      "A dog who thinks he's a cat...",
      "A parrot who only repeats knock-knock jokes...",
      "A hamster who runs a detective agency...",
      "A goldfish with a secret identity...",
      "A turtle who dreams of being a race car driver...",
      "A rabbit who can't stop giggling...",
      "A squirrel who collects rubber bands...",
      "A bear who is afraid of honey...",
      "A lion who wants to be a vegetarian...",
      "A penguin who loves the desert...",
      "A monkey who opens a banana stand...",
      "A giraffe who wants to be a basketball player...",
      "A mouse who is the school principal...",
      "A snake who can't stop tying itself in knots...",
      "A kangaroo with a trampoline in its pouch...",
      "A pig who wants to be a ballet dancer...",
      "A horse who loves to paint...",
      "A chicken who is afraid of eggs...",
      "A duck who wants to be a lifeguard...",
      "A cow who dreams of being a rock star...",
      "A sheep who can't stop bouncing...",
      "A goat who loves to knit...",
      "A fox who is terrible at hide and seek...",
      "A wolf who wants to be a vegetarian chef..."
    ]
  },
  {
    name: "School",
    description: "Classroom antics, teachers, and schoolyard fun.",
    templates: [
      "A substitute teacher who is actually a robot...",
      "A lunch lady who serves invisible food...",
      "A principal who moonlights as a magician...",
      "A class pet who runs for student council...",
      "A spelling bee where the words spell themselves...",
      "A math test with questions about pizza...",
      "A science experiment that grows a giant tomato...",
      "A gym class where everyone must hop...",
      "A music teacher who only plays kazoo...",
      "A field trip to the moon...",
      "A school bus that tells jokes...",
      "A classroom where the desks dance...",
      "A teacher who can't stop hiccuping...",
      "A library book that reads itself...",
      "A janitor who is secretly a superhero...",
      "A school play with a surprise ending...",
      "A cafeteria food fight with spaghetti...",
      "A history lesson taught by a talking statue...",
      "A fire drill that turns into a water balloon fight...",
      "A pop quiz with only silly questions...",
      "A school nurse who prescribes laughter...",
      "A classroom pet who writes poetry...",
      "A student who invents a homework-eating robot...",
      "A teacher who gives out gold stars for burping...",
      "A school bell that rings with a different animal sound every day..."
    ]
  },
  {
    name: "Superheroes",
    description: "Unusual powers, heroic deeds, and comic misadventures.",
    templates: [
      "A superhero whose only power is making people laugh...",
      "A villain who is allergic to evil...",
      "A sidekick who is always late...",
      "A superhero who can turn invisible, but only when no one is looking...",
      "A hero who can fly, but only backwards...",
      "A villain who loves to bake cookies...",
      "A superhero with a cape that won't stop shrinking...",
      "A hero whose superpower is super sneezing...",
      "A villain who is afraid of kittens...",
      "A superhero who can talk to vegetables...",
      "A hero who can run fast, but only in circles...",
      "A villain who can't stop telling puns...",
      "A superhero who is afraid of heights...",
      "A hero who can stretch, but only their ears...",
      "A villain who wants to be a stand-up comedian...",
      "A superhero whose costume is always inside out...",
      "A hero who can turn anything into cheese...",
      "A villain who is obsessed with rubber ducks...",
      "A superhero who can only save the day on weekends...",
      "A hero who can talk to animals, but they only tell jokes...",
      "A villain who is really just misunderstood...",
      "A superhero who can make it rain spaghetti...",
      "A hero who can teleport, but only to the nearest bathroom...",
      "A villain who is afraid of their own shadow...",
      "A superhero whose secret identity is a lunch lady..."
    ]
  },
  {
    name: "Friendship",
    description: "Bonds, teamwork, and funny misunderstandings.",
    templates: [
      "Two best friends accidentally swap lunches...",
      "A group of friends starts a band, but no one can play an instrument...",
      "A friendship bracelet with magical powers...",
      "A sleepover that turns into a pillow fort war...",
      "A secret handshake that causes giggles...",
      "A best friend who is actually a robot...",
      "A group project that goes hilariously wrong...",
      "A friendship test with silly questions...",
      "A friend who always tells tall tales...",
      "A friendship that starts with a pie in the face...",
      "A friend who is afraid of their own shadow...",
      "A group of friends who start a detective club...",
      "A friendship that survives a food fight...",
      "A friend who can only speak in rhymes...",
      "A friendship that begins with a lost shoe...",
      "A friend who is always late, but always brings snacks...",
      "A group of friends who invent a new game...",
      "A friendship that is tested by a silly rumor...",
      "A friend who is a master of pranks...",
      "A friendship that starts with a shared umbrella...",
      "A friend who loves to tell jokes...",
      "A group of friends who build a treehouse...",
      "A friendship that survives a haunted house...",
      "A friend who is obsessed with rubber ducks...",
      "A friendship that begins with a sneeze..."
    ]
  },
  {
    name: "Holidays",
    description: "Festive fun, traditions, and holiday mishaps.",
    templates: [
      "A Halloween costume that comes to life...",
      "A Thanksgiving turkey that runs away...",
      "A Christmas tree that sings carols...",
      "A New Year's Eve party with a surprise guest...",
      "A Valentine's Day card with a secret message...",
      "A birthday cake that explodes with confetti...",
      "A holiday parade with dancing vegetables...",
      "A snowman who wants to go to the beach...",
      "A holiday dinner where the food fights back...",
      "A Fourth of July picnic with fireworks that spell jokes...",
      "A holiday gift that keeps disappearing...",
      "A St. Patrick's Day leprechaun who loves pizza...",
      "A holiday play with a surprise ending...",
      "A holiday card that tells jokes...",
      "A holiday tradition that involves rubber chickens...",
      "A holiday party with a food fight...",
      "A holiday song that makes everyone dance...",
      "A holiday pet who causes chaos...",
      "A holiday wish that comes true in a silly way...",
      "A holiday prank war...",
      "A holiday dinner with invisible food...",
      "A holiday parade with bouncing balloons...",
      "A holiday gift that tells jokes...",
      "A holiday tree that grows candy...",
      "A holiday snowball fight in July..."
    ]
  },
  {
    name: "Food",
    description: "Cooking, eating, and food-related adventures.",
    templates: [
      "A pizza that wants to be a pie...",
      "A chef who only cooks with jellybeans...",
      "A food fight that turns into a dance party...",
      "A sandwich that tells jokes...",
      "A cake that sings happy birthday...",
      "A salad that wants to be a dessert...",
      "A soup that tells fortunes...",
      "A fruit bowl with a secret...",
      "A pancake that flips itself...",
      "A cookie that runs away...",
      "A spaghetti monster in the cafeteria...",
      "A lunchbox with a mind of its own...",
      "A chef who can't stop sneezing...",
      "A food truck that only serves breakfast...",
      "A pie-eating contest with invisible pies...",
      "A kitchen where the utensils dance...",
      "A recipe that changes every time it's read...",
      "A food critic who is a dog...",
      "A restaurant where the customers cook...",
      "A chef who only cooks in rhyme...",
      "A food festival with bouncing vegetables...",
      "A dessert that tells jokes...",
      "A picnic interrupted by ants with a plan...",
      "A breakfast that lasts all day...",
      "A dinner party with surprise guests..."
    ]
  },
  {
    name: "Nature",
    description: "Outdoor adventures, weather, and funny animal encounters.",
    templates: [
      "A rainstorm that makes everyone dance...",
      "A picnic invaded by squirrels...",
      "A camping trip with a tent that snores...",
      "A hike where the trail signs tell jokes...",
      "A garden where the flowers sing...",
      "A treehouse that grows higher every night...",
      "A river that flows backwards...",
      "A mountain that tells stories...",
      "A beach where the sand makes funny noises...",
      "A thunderstorm that giggles...",
      "A rainbow that leads to a joke shop...",
      "A snowstorm in July...",
      "A forest where the trees play hide and seek...",
      "A pond with a talking frog...",
      "A field of bouncing bunnies...",
      "A windy day that blows everyone's hats away...",
      "A garden gnome who tells riddles...",
      "A butterfly who can't stop sneezing...",
      "A picnic where the food floats...",
      "A tree that grows rubber chickens...",
      "A cloud shaped like a banana...",
      "A thunderstorm that tells jokes...",
      "A river that sings lullabies...",
      "A mountain that moves...",
      "A beach where the waves clap..."
    ]
  },
  {
    name: "History",
    description: "Time travel, famous figures, and silly historical twists.",
    templates: [
      "A time traveler who forgets what year it is...",
      "A knight who invents the first skateboard...",
      "A pharaoh who loves pizza...",
      "A caveman who invents the whoopee cushion...",
      "A queen who loves to tell jokes...",
      "A pirate who is afraid of water...",
      "A president who only speaks in rhyme...",
      "A famous inventor who can't stop sneezing...",
      "A gladiator who loves to knit...",
      "A king who is obsessed with rubber ducks...",
      "A time machine that only goes to lunchtime...",
      "A famous explorer who gets lost in their own house...",
      "A painter who paints with spaghetti...",
      "A scientist who invents a joke-telling robot...",
      "A famous musician who plays the kazoo...",
      "A cowboy who rides a unicycle...",
      "A samurai who loves to bake cookies...",
      "A viking who is afraid of loud noises...",
      "A famous poet who only writes limericks...",
      "A time traveler who brings back rubber chickens...",
      "A pharaoh who loves to dance...",
      "A knight who is afraid of dragons...",
      "A queen who loves mud pies...",
      "A pirate who collects rubber bands...",
      "A president who loves to play pranks..."
    ]
  }
];
